dbt_sigma_poc:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: sigmacomputing_poc
      password: leaflink123
      dbname: dbt_sigma_poc
      schema: hospital_beds
      threads: 2
      keepalives_idle: 0
      connect_timeout: 10
