version: 2

models:
  - name: staff_base
    description: >
      Base view over raw staff with one row per staff member.
      Source: public.staff (seeded from Kaggle hospital beds dataset).
    tags: ["poc", "base"]
    columns:
      - name: staff_id
        description: Unique identifier for a staff member.
        tags: ["primary_key"]
        tests:
          - not_null
          - unique
      - name: staff_name
        description: Full display name for the staff member.
        tests:
          - not_null
      - name: role
        description: Role/title of the staff member (e.g., Nurse, Physician, Admin).
        tests:
          - not_null
      - name: service
        description: Service or department assignment (e.g., ICU, ER, Pediatrics).
        tests:
          - not_null

  - name: staff_schedule_base
    description: >
      Weekly staff presence by service and role. One row per staff member per week,
      indicating whether they were present. Source: public.staff_schedule.
    tags: ["poc", "base"]
    tests:
      # Composite business key should be unique per week/staff member.
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ["week", "staff_id"]
    columns:
      - name: week
        description: Week identifier (e.g., ISO week start date); granularity of the schedule.
        tags: ["primary_key"]  # part of composite PK with staff_id
        tests:
          - not_null
      - name: staff_id
        description: Staff identifier; references staff_base.staff_id.
        tags: ["primary_key", "foreign_key"]
        meta:
          references:
            model: ref('staff_base')
            column: staff_id
        tests:
          - not_null
          - relationships:
              to: ref('staff_base')
              field: staff_id
      - name: staff_name
        description: Staff display name (denormalized for convenience; should match staff_base.staff_name).
      - name: role
        description: Role/title for the scheduled staff member.
      - name: service
        description: Service or department for which the staff member is scheduled.
      - name: present
        description: Boolean flag indicating whether the staff member was present that week.
        tests:
          - not_null
